### ISSUE TITLE
Caching policies

### ISSUE THREAD

**Issue by Seirdy** [sesh/ready#11]
ready could run the following checks:

- Cache-Control headers are present for nontrivial responses.
- Static assets support cache-busting and have an immutable directive (see Webhint's guidance for reference).
- HTML responses aren't cached for longer than 24h.
- No p3p headers exist.

**Comment by sesh** [comment]
Thanks for the series of suggestions @Seirdy. I'll set aside some time tomorrow to review and implement them.

**Comment by sesh** [comment]
I've added checks for `p3p` and `max-age` being below 24 hours.

There is already a check for `Cache-Control` being in the response (I'm assuming this tool will only be used to test non-trivial responses).

For static assets I think it's best to use webhint or pagespeed. I'm not keen to start requesting assets referred to on the page. I've added links to both of these in the "other tools" section of the README.
