### ISSUE TITLE
Certificate revocation

### ISSUE THREAD

**Issue by Seirdy** [sesh/ready#15]
`ready` currently reports a pass if a certificate is trusted. It could benefit from giving revocation information as well by reporting on:

- OCSP stapling/must-staple, or a short certificate lifetime (Firefox ignores OCSP if the certificate lifetime is under 10 days).
- CRLsets/CRLite/Let's Revoke information (similar to what testssl.sh supports).

In-depth TLS analysis may be out of scope and better suited for a tool like testssl.sh or Internet.nl, but a simple revocation check could work. At the very least: it could warn if OCSP stapling isn't set up for certificates with normal lifetimes (>10 days), and perhaps encourage them to use must-staple.

**Comment by sesh** [comment]
A check for OCSP stapling makes total sense to me.

A couple of notes from my quick investigation this morning.

`getpeercert()` doesn't return whether must-staple is enabled by the looks of things. It does return an OCSP value but that appears to be from the information access section.

Running the der file (from: `getperrcert(binary_form=True)`) through openssl (`openssl x509 -in cert.der -inform der -text`) does output the "1.3.6.1.4.1.11129.2.4.2" block.

**Comment by sesh** [comment]
Here's a cpython issue about adding support for extensions to the `getpeercert` function:
https://github.com/python/cpython/issues/64668

The suggestion there is to use `pyasn1` or similar.

**Comment by sesh** [comment]
Okay, so the `pyasn1` rabbit whole has ended up with a couple of other interesting libraries that we could use here.

`asn1crypto` lets you load DER files with the extensions. Then `certvalidator` wraps that with a bunch of (very appropriate) validation rules:

https://github.com/wbond/certvalidator/

If I implement something beyond simply checking for the "OCSP" value in the certificate than I expect that it would end up using this library.

**Comment by Seirdy** [comment]
Sounds good. How do you feel about checking for "must-staple"? Without OCSP Must-Staple, I don't think stapling is anything more than a privacy measure to reduce traffic leakage to CAs because failures are silently ignored.
