### ISSUE TITLE
'Expires' timestamp not checked in 'security.txt'?

### ISSUE THREAD

**Issue by mejofi** [sesh/ready#18]
**Version**: 1.1.1

As far as I can tell, the 'Security.txt exists and is a text file that contains required attributes' test does not check if the 'Expires' line, which is required by spec, isn't in the past.

Example; `Expires: 2024-02-09T22:59:00.000Z` passes with an OK, despite being expired, and should therefore not be considered production ready?

Don't know how difficult it is to add this, but it would be appreciated as an extra check 🙂

This is with a 'security.txt' generated via https://securitytxt.org

**Comment by sesh** [comment]
This is a great suggestion. I've added a quick check and created a sample domain for testing:
securitytxt-expired-test.b5n.sh

**Comment by sesh** [comment]
```
> ready securitytxt-expired-test.b5n.sh | grep -i "security.txt"
[ OK ] Security.txt exists and is a text file that contains required attributes
[FAIL] Security.txt has an expiry date in the future (2023-01-01 00:00:00+00:00)
```
