### ISSUE TITLE
Parse error in Cache-Control max-age test?

### ISSUE THREAD

**Issue by mejofi** [sesh/ready#27]
**Version**: 1.2.3 (and 1.2.2)

Just noticed the following;
```
[ OK ] Cache-Control max-age should be <= 86400 for HTML documents (parse error: max-age=86400)
```
It passes, but shows a 'parse error'? Is that an actual error, or something else?

**Comment by sesh** [comment]
Looks like this one is just a mistake in the output. I must have copied the "parse error" into the success output at some point. I've updated it and will release the change as v1.2.4.

Thanks for all these reports, btw!
